// Generated by CoffeeScript 1.6.3
(function() {
  var Parser, fs;

  fs = require('fs');

  Parser = require('./parser');

  module.exports = {
    parse: function(str) {
      var p;
      p = new Parser;
      return p.parse(str);
    },
    parseFile: function(file) {
      var str;
      str = fs.readSync(file, {
        encoding: 'utf-8'
      });
      return this.parse(str);
    }
  };

}).call(this);
