// Generated by CoffeeScript 1.6.3
(function() {
  var fs, parse;

  fs = require('fs');

  parse = require('./parser');

  module.exports = {
    parse: function(str, options) {
      if (options == null) {
        options = {};
      }
      return parse(str, options);
    },
    parseFile: function(file, options) {
      var str;
      str = fs.readSync(file, {
        encoding: 'utf-8'
      });
      return this.parse(str, options);
    }
  };

}).call(this);
